### ISSUE TITLE
Windowsの配布バイナリで "An assembly specified in the application dependencies manifest" が出る

### ISSUE THREAD

**Issue by esehara** [tategakibunko/TypeNovel#1]
# 問題

`Windows 10` 下でバイナリファイルをダウンロードし、解凍して利用しようとしたところ、以下のようなエラーが出てしまいました。

```
C:\Users\eseha\Tnc>tnc testnovel.tc
Error:
  An assembly specified in the application dependencies manifest (Tnc.deps.json) was not found:
    package: 'Argu', version: '5.5.0'
    path: 'lib/netstandard2.0/Argu.dll'
```

何らかのパッケージ依存が解決されていないと考え、`.NET Core 2.2` をインストールした後に、再起動も試してみましたが、依然として同じ問題が出てきてしまいます。

もしかすると、同じような問題で試すことが出来ない人もいるかと考え、Issueで投げてみることにしました。よろしくお願いします。

# 環境

- Windows 10
- .NET Core 2.2 インストール済

**Comment by tategakibunko** [comment]
当方、Windows環境を持っていないため、こういう報告は助かります。ありがとうございます。

おそらく、こちらが何かしらのパッケージングミスをしたのだと思います。

そこでちょっとだけ（ダメ元で）試していただきたいのですが、

```bash
dotnet add package Argu --version 5.5.0
```

などとしても駄目でしょうか？

自分としても.NET Coreというのを使って開発するのが今回が初めてなので、色々と手探りな状態です。ご面倒おかけして申し訳ないです。

<追記>

もしかして、と思ったので念のため聞かせていただきたいのですが、解凍すると`Tnc.exe`以外にも、その他のファイルがいっぱい入ったフォルダーが展開されると思います。で、もしかしてexeファイルだけを単独で別のフォルダに入れて実行したとかはないでしょうか？

フォルダの中に入ってるその他色々なファイルは、`Tnc.exe`を実行するために必要なDLLとかが入ってるので、それだとうまくいかないかもしれません。

**Comment by esehara** [comment]
お返事ならびに対応ありがとうございます。

`dotnet add package Argu --version 5.5.0` を試してみたのですが、これ自体は、どうやら元々あるプロジェクトにライブラリを追加するコマンドのようなので、配布されているバイナリ自体に対して行っても、上手くいかないようです。以下のようなエラーがでます:

```
C:\Users\eseha\Downloads\Tnc\` にプロジェクトが見つかりませんでした。
```

そこで、プロジェクト全体をダウンロードし、
```
dotnet publish -c Release -r win-x64 --self-contained true` 
```
[参考サイト](https://kagasu.hatenablog.com/entry/2017/04/16/192117)

を実行してバイナリを作成し、それを使ったところ、動くバイナリが出来ました。もう既に試されているかもしれませんが、ここに書いておきます。

※追記に関しては、ダウンロードして、ファイル全体を解凍したフォルダ内で実行しているので、自分が解凍に失敗していなければ、圧縮ファイル内に入っているファイルが揃った状態で実行している筈です。

**Comment by tategakibunko** [comment]
ありがとうございます！

実はコンパイルに関しては、ご指摘のサイトを自分も参考にしてまして、全く同じコマンドでコンパイルしているはずなのですが…

https://github.com/tategakibunko/TypeNovel/blob/master/Tnc/Makefile

どうやら同じコンパイル動作でも、MacからコンパイルするとWinで動くバイナリができないみたいですね。クロスコンパイルとはなんだったのか（笑）。

**Comment by tategakibunko** [comment]
zipする範囲を変えたものを以下にアップしました。

https://github.com/tategakibunko/TypeNovel/tree/master/Archives/Win/TypeNovel-0.9.0.zip

(旧) `Tnc/bin/Release/netcoreapp2.2/win-x64/`
(新) `Tnc/bin/Release/netcoreapp2.2/win-x64/publish`

旧型のzipは、`Tnc.exe`がルートディレクトリと`publish`ディレクトリの双方にありました。

で、どうもスタンドアロン型での`Tnc.exe`は`publish`ディレクトリの中のものを指すようです。同じディレクトリにたくさんdllがありますので。

つまり今までの`Tnc.exe`も、展開した先のルートディレクトリのものではなく、`publish`ディレクトリの中のものを実行したら、普通に動いていたかと思われます。

とはいえまだ確定ではないので、ユーザーさんの報告を待って「無事に起動した」という報告があったら、このIssueを閉じたいと思います。
